import Aside from "../components/Aside";
import Section from "../components/Section";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <>
      <Section />
      <Aside />
    </>
  )
}
